version: "3.8"

services:
  server:
    container_name: gin-server
    build:
      context: ./SQLXpertRestApi
      dockerfile: Dockerfile.dev
    ports:
      - "7676:7676"
    environment:
      PORT: 7676
    links:
      - web-client
    volumes:
      - ./SQLXpertRestApi:/app

  web-client:
    container_name: nextjs
    build:
      context: ./SQLXpertWebClient/
      dockerfile: Dockerfile
    ports:
      - "7677:5173"
    environment:
      PORT: 5173
    volumes:
      - ./SQLXpertWebClient:/app
    command: sh -c 'npm run dev --host'
